import type { Metadata } from "next";
import localFont from "next/font/local";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "../globals.css";
import { reader } from "@/app/reader";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await reader.singletons.navbar.read();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <Header data={data} />
          <main className="pt-[60px] bg-[linear-gradient(236.22deg,_#1D3D8D_1.39%,_#14244C_90.45%)]"> {/* Adjust height based on your Header */}
            {children}
          </main>
        </AntdRegistry>
      </body>
    </html>
  );
}
